// This file is generated by build.rs. Do not edit it manually.
use std::collections::HashMap;
use lazy_static::lazy_static;
lazy_static! {
pub static ref KERNELS: HashMap<&'static str, &'static str> = {
    let mut m = HashMap::new();
    m.insert("qgemm_vec4", include_str!("/Users/fleetwood/Code/ratchet/crates/ratchet-core/kernels/qgemm_vec4.wgsl"));
    m.insert("sgemm_scalar", include_str!("/Users/fleetwood/Code/ratchet/crates/ratchet-core/kernels/sgemm_scalar.wgsl"));
    m.insert("add_scalar", include_str!("/Users/fleetwood/Code/ratchet/crates/ratchet-core/kernels/add_scalar.wgsl"));
    m
};
}
