// This file is generated by build.rs. Do not edit it manually.
pub static KERNELS: &[(&str, &str)] = &[
("qgemm_vec4", include_str!(r"/Users/fleetwood/Code/ratchet/crates/ratchet-core/kernels/qgemm_vec4.wgsl")),
("add_scalar", include_str!(r"/Users/fleetwood/Code/ratchet/crates/ratchet-core/kernels/add_scalar.wgsl")),
];
