[package]
name = "ratchet-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
ratchet = { path = "../ratchet-core" }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tch = "0.16.0"
torch-sys = "0.16.0"
